### ISSUE TITLE
Render as link option not working

### ISSUE THREAD

**Issue by ChristopherBull** [snuids/trafficlights-panel#12]
When setting the option to render as link, the cursor will change to the expected 'pointer' style, but there is no link data. Nothing happens when I click (on the text or the traffic light). The URL I eneter in the traffic light options does not even display in the browser's URL display in the bottom right. The tooltip I enter also does not display when I mouseover. It seems like the traffic light is being rendered as a link, but none of the link data is being applied.

Tested in Chrome (78.0.3904.108) and Firefox (70.0.1).

When I do the same with the built-in Table panel, it works as expected. Not sure if that helps, as I am not sure if they share any underlying mechanisms.

**Comment by eriklouise** [comment]
Hi,

Same issue here, seems to be related to Grafana 6.5.0. My very same dashboards with links on trafficlights panels were working fine on Grafana 6.4.4.

So ... I reverted back to Grafana 6.4.4 for now.

**Comment by ChristopherBull** [comment]
Now works.

Grafana released v6.5.1, which fixes the issue.

Probably related to this PR:
https://github.com/grafana/grafana/pull/20696
