### ISSUE TITLE
Center traffic lights

### ISSUE THREAD

**Issue by roidelapluie** [snuids/trafficlights-panel#2]
Hi

Would be nice to center the traffic lights

![ctr](https://user-images.githubusercontent.com/291750/32099826-3ca4e73a-bb12-11e7-8eda-5e5592c7be73.png)

**Comment by snuids** [comment]
Simply put the same number of traffic lights per line as the number of results you get.
Are you living in Belgium ?

**Comment by roidelapluie** [comment]
Yes I am. weli I just have 3 lights.

**Comment by snuids** [comment]
So if you put 3 traffic lights per line in the options, this would do the trick.

Bon Week-End

**Comment by roidelapluie** [comment]
But I do not know it advance the number....

**Comment by snuids** [comment]
Done in version 5.3. Option (Spread traffic lights)

**Comment by roidelapluie** [comment]
very cool :) Will test that asap
