### ISSUE TITLE
Missing signature for plugin

### ISSUE THREAD

**Issue by R0peE** [snuids/trafficlights-panel#30]
Hi Arnaud,

Would it be possible to create a signature for the plugin by the doc: https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

Currently in grafana 7.2 the plugin is not loading as it is unsigned, and i have to explicitly allow it to appear:

![image](https://user-images.githubusercontent.com/5132449/148787394-05324c10-e459-46ce-b0e4-ebde7e41013b.png)

Thanks in advance!

**Comment by snuids** [comment]
In fact I was stuck by the fact that the grafana public repository is deprecated . I simply signed my plugin using the npx command and commit it.

Then I updated it. Hope it will unblock the process.

Thanks for the help.

**Comment by R0peE** [comment]
Your help and effort is much appreciated! Thanks!

**Comment by snuids** [comment]
You are welcome. Would like to participate more if I had time :-) Enjoy the rest of the day.
