### ISSUE TITLE
Invert scale produces unexpected results

### ISSUE THREAD

**Issue by roidelapluie** [snuids/trafficlights-panel#4]
![ligh1](https://user-images.githubusercontent.com/291750/32101770-dd4a3576-bb19-11e7-8201-7b6f74f10689.png)
![ligh2](https://user-images.githubusercontent.com/291750/32101771-dd782d32-bb19-11e7-8614-18c9d1fb577a.png)

**Comment by snuids** [comment]
You simply need to invert the green and red values in this case because green threshold must be below red threshold.

**Comment by snuids** [comment]
I added a few validations in the option panel that helps the configuration.
