### ISSUE TITLE
Ordering of lights

### ISSUE THREAD

**Issue by pkropf** [snuids/trafficlights-panel#5]
I have a dashboard with two rows and a series of traffic lights that show status of services. Each row shows the same services just from a different server's point of view. I'd like to be able to order the traffic lights in each row to align with the other row. Would it be possible to do that?

![screenshot_2018-07-31_09-10-15](https://user-images.githubusercontent.com/99347/43472304-fca31f98-94a1-11e8-9d34-6b8f18324ab3.png)

**Comment by snuids** [comment]
@pkropf

Which type of database are you using, you should be able to order the traffic lights from the datasource.

**Comment by pkropf** [comment]
Data is coming from an InfluxDB database.

How does the order of the data in the database related to presenting it in Grafana?

**Comment by snuids** [comment]
Depending on the database you are using, there are more or less options in the grafana datasource editor. Unfortunately, it looks like there is no ordering for Influx. I am mainly using Elastic and never had this problem.

I will think of it and try to add the option when I have a few hours to spare.

Cheers,

Arnaud

**Comment by pkropf** [comment]
Appreciated! It is a low priority but would be nice to have.

**Comment by snuids** [comment]
@pkropf
Added a sort option in v1.4.4. Can you give it a try ?

Cheers,

Arnaud

**Comment by pkropf** [comment]
Works great, thanks!
